# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 https://sanderbeckers.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             /website

title:               Sander

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Welcome to the personal webpage of Sander Beckers 

# The tags listed as entries in the sidebar
sidebar_tags:        [articles, talks, cv]

# Fallback image and color if not overwritten for tag or post
image:               /website/sander/background44.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Sander Beckers'

  # This photo will be used in the about section
  photo:             /website/sander/profile_picture_2.jpg
  #photo2x:          

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about: |
   Welcome to my personal webpage, and thanks for taking the time to have a look! I am currently a postdoctoral researcher in [the Causality in Healthcare AI hub](https://www.chai.ac.uk/), under the supervision of [Ricardo Silva](https://www.homepages.ucl.ac.uk/~ucgtrbd/) at [the Department of Statistical Science, University College London](https://www.ucl.ac.uk/mathematical-physical-sciences/statistics).
   
   I work in the field of causality. Causality does not belong to any specific discipline, but rather is a research field that cuts across many disciplines, including but not limited to philosophy of science, Artificial Intelligence, statistics, and logic. This interdisciplinarity is reflected in both my education, employment, and most notably, my research. Although causality as a topic has a long history, the contemporary field of causality only took off several decades ago and it has been expanding ever since. Different frameworks for expressing causal notions exist, and my work so far has taken place mostly within the formal interventionist framework that uses Structural Causal Models and Causal Bayesian Networks as the causal models of choice. My contributions so far can roughly be grouped into three overlapping categories. 

   First, I have used causal models to construct and discuss formal definitions of actual causation and their properties. Instead of only looking at how well such definitions match up with alleged intuitions about causation, I construct and justify my definitions in a more systematic, principled, and functionalist manner.

   Second, I use the expressiveness of the causal modelling framework combined with definitions of actual causation to formally define other important notions, such as harm, responsibility, and explanation. The underlying motivation to formally define these notions is twofold: they form crucial tools both to develop and conceptualize ethical AI, and they contribute to the more general philosophical literature on these topics. 

   Third, I work on extending the framework of causal models itself, so that they can express a wider range of relations that we are interested in. For example, my work on causal abstraction makes precise how to represent the relation between two causal models that describe the same system at different levels of abstraction. My work on backtracking counterfactuals and on nondeterministic causal models generalizes the existing semantics of causal counterfactuals to allow for novel types of applications, ranging from the use of causal models to interpret causal claims in history, offer better methods for explainable AI, reason about counterfactuals of Large Language Models, form a compromize in a heated debate about causing harm in precision medicine, and much more.  This line of work is also of significance to discussions in the philosophy of science on reductionism and inter-level causation, the emergence of nondeterminism in a deterministic world, and the role of counterfactuals in causal inference, amongst others.

   Although so far most of my work (but not all) has involved causality, I have very broad philosophical and AI-related interests and do intend to widen the scope of my research significantly. (I just need to fix all issues involving causality first... Just kidding!) Despite the fact that I have been working within and across a variety of disciplines for many years, I am still first and foremost a philosopher, as I truly believe that a philosophical attitude can contribute to any scientific and social domain. Most importantly, it is the only attitude I know of that can make it bearable at least, and life-changing at best, to think about literally any topic or problem.

   Feel free to send me an e-mail if you would like to get in touch:  srekcebrednas_[fill in appropriate symbol]_gmail.com

   [Google Scholar page](https://scholar.google.com/citations?user=7aqN2U4AAAAJ&hl=en)

     
  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    #facebook:        bedenkzelfiets 
    #twitter:         _username_
    #google:          _number_
    #vk:              _username_
    #youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # github:          _username_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        sander-beckers-00136aab
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Analytics
google_analytics_id: 'UA-92275247-1'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
