# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 https://sanderbeckers.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             /website

title:               Sander

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Welcome to the personal webpage of Sander Beckers 

# The tags listed as entries in the sidebar
sidebar_tags:        [articles, talks, cv]

# Fallback image and color if not overwritten for tag or post
image:               /website/sander/background44.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Sander Beckers'

  # This photo will be used in the about section
  photo:             /website/sander/profile_picture.jpg
  #photo2x:          

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about: |
   Welcome to my personal webpage, and thanks for taking the time to have a look! I am currently a postdoctoral member of the [Cluster of Excellence in Machine Learning, at the University of Tübingen](https://uni-tuebingen.de/en/research/core-research/cluster-of-excellence-machine-learning/research/research/cluster-research-groups/research-groups/epistemology-and-ethics-of-ml/). I am currently continuing my work on a wide variety of topics involving causation and causal modeling that I started during my previous position as a Humboldt fellow at the [Munich Center for Mathematical Philosophy](https://www.mcmp.philosophie.uni-muenchen.de/index.html). 
   
   Before that, I was a postdoctoral researcher at the Department of Philosophy and Religious Studies, Utrecht University, where I worked under the supervision of [Jan Broersen](http://www.staff.science.uu.nl/~broer110/),
   as part of the [REINS project.](https://responsibleintelligentsystems.sites.uu.nl)
   
   There I focussed on formalizing the concept of moral responsibility. The goal was to engage both with philosophical problems surrounding the notion of responsibility, as well as with ethical and practical issues that show up when thinking of responsibility in the context of Artificial Intelligence.
    
   Before coming to Utrecht, I was invited by [James Conant](http://philosophy.uchicago.edu/faculty/conant.html) to spend two months at Leipzig University, Institute of Philosophy. 
   There I worked on interpreting Wittgenstein’s Tractatus Logico-Philosophicus, a topic to which I hope to return one day. 
   
   During the 2016-17 academic year I was a [B.A.E.F.](http://www.baef.be/documents/home.xml?lang=en)-research fellow at Cornell University, Department of Computer Science, where I worked under the supervision of [Joe Halpern](https://www.cs.cornell.edu/home/halpern/). 
   
   Prior to my stay at Cornell I obtained a PhD investigating the topic of Actual Causation at the University of Leuven, Department of Computer Science, under the supervision of [Joost Vennekens](https://people.cs.kuleuven.be/~joost.vennekens/). Part of my current research is an extension of my work on causation into formal ethics. Concretely, I work on formalising definitions of responsibility, intention, and blameworthiness, taking formal definitions of causation as my starting point. 
   
   However my interests are not limited to these problems but span a much wider range of topics, such as the ethics of AI, the (ir)rationality of belief in the supernatural, philosophy of mathematics, bounded rationality, the philosophy of Wittgenstein, cultural relativism, and many more. 
   
   Feel free to send me an e-mail if you would like to get in touch:  <a href="mailto:srekcebrednas@gmail.com?Subject=Job%20Offer%20from%20[Fill%20in%20your%20prestigious%20university]" target="_top">srekcebrednas@gmail.com</a>. 

     
  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    facebook:        bedenkzelfiets 
    #twitter:         _username_
    #google:          _number_
    #vk:              _username_
    #youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # github:          _username_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    linkedin:        sander-beckers-00136aab
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Analytics
google_analytics_id: 'UA-92275247-1'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
