# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 https://sanderbeckers.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             /website

title:               Sander

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Welcome to the personal webpage of Sander Beckers 

# The tags listed as entries in the sidebar
sidebar_tags:        [articles, talks, cv]

# Fallback image and color if not overwritten for tag or post
image:               /website/sander/background44.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Sander Beckers'

  # This photo will be used in the about section
  photo:             /website/sander/profile_picture_2.jpg
  #photo2x:          

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about: |
   Welcome to my personal webpage, and thanks for taking the time to have a look! I am currently a postdoctoral researcher at [the Department of Computer Science, Cornell University](https://www.cs.cornell.edu).
   
   Here I continue my work on a wide variety of topics involving causation and causal modeling. Roughly, my existing work can be grouped into three categories. 
   
   First, I use causal models to construct and discuss formal definitions of actual causation and their properties. Instead of only looking at how well such definitions match up with alleged intuitions about causation, I aim to justify my definitions in a more systematic and principled way. 
   
   Second, I use the combination of causal models and definitions of actual causation to formally define other important notions, such as harm, responsibility, and explanation. The underlying motivation to formally define these notions is twofold: they offer useful tools to develop ethical AI, and they contribute to the more general philosophical literature on these topics. 
   
   Third, I work on extending the framework of causal models itself, so that they can express a wider range of relations that we are interested in. For example, my work on causal abstraction makes precise how to represent the relation between two causal models that describe the same system at different levels of abstraction. Other work in progress aims to generalize even further, so that we can combine variables which share causal and non-causal relations with each other into a single model. 
   This line of work also holds promise for discussions in the philosophy of science on reductionism and inter-level causation. 
   
   Although so far most of my work (but not all) has involved causality, I have very broad philosophical interests and do intend to widen the scope of my research significantly. (I just need to fix all issues involving causality first... Just kidding!) Despite the fact that I have been working within AI for many years, I am still first and foremost a philosopher, and my philosophical interests branch out to diverse areas that encompass the philosophy of Wittgenstein, the limitations of scientific knowledge, cultural relativism, any topic in formal philosophy, and many more.   

   Feel free to send me an e-mail if you would like to get in touch:  <a href="mailto:srekcebrednas@gmail.com?Subject=Job%20Offer%20from%20[Fill%20in%20your%20prestigious%20university]" target="_top">srekcebrednas@gmail.com</a>. 

   [Google Scholar page](https://scholar.google.com/citations?user=7aqN2U4AAAAJ&hl=en)

     
  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    #facebook:        bedenkzelfiets 
    #twitter:         _username_
    #google:          _number_
    #vk:              _username_
    #youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # github:          _username_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        sander-beckers-00136aab
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Analytics
google_analytics_id: 'UA-92275247-1'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
